# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: scheduled_flow.yml

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create service account JSON file
        run: echo '${{ secrets.MATCHING_SERVICE_ACCOUNT }}' > matching-service-account.json

      - name: Run alrawdha_matrimonial_workflows

        env:
          SERVICE_ACCOUNT_FILE: matching-service-account.json
          RAW_PROFILE_GENERATOR: ${{ secrets.RAW_PROFILE_GENERATOR }}
          PROC_PROFILE_GENERATOR: ${{ secrets.PROC_PROFILE_GENERATOR }}
          RAW_MATCH_REQUEST: ${{ secrets.RAW_MATCH_REQUEST }}
          PROC_MATCH_REQUEST: ${{ secrets.PROC_MATCH_REQUEST }}
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}

        run: |
          mkdir -p data
          python profile_generator.py
          python match_request.py

      - name: Cleanup generated PDFs
        if: always()
        run: rm -rf data
