# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: scheduled_workflow.yml

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create service account JSON file
        run: echo '${{ secrets.SERVICE_ACCOUNT_JSON }}' > matching-service-account.json

      - name: Run alrawdha_matrimonial_workflows

        env:
          SERVICE_ACCOUNT_JSON: matching-service-account.json
          RAW_PROFILE_GENERATOR: ${{ secrets.RAW_PROFILE_GENERATOR }}
          AMMENDED_PROFILE_GENERATOR: ${{ secrets.AMMENDED_PROFILE_GENERATOR }}
          PROC_PROFILE_GENERATOR: ${{ secrets.PROC_PROFILE_GENERATOR }}
          POST_M_PROF: ${{ secrets.POST_M_PROF }}
          POST_F_PROF: ${{ secrets.POST_F_PROF }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}

        run: |
          mkdir -p data
          python 1_profile_generator.py
          python 2_profile_checker.py
          python 3_telegram_bot.py

      - name: Cleanup generated PDFs
        if: always()

        run: |
          rm -f service_account.json
          rm -f .env
          rm -rf data
